### PR TITLE
Types

### PR DESCRIPTION
**Pull request by jamescdavis**
This adds type definitions that augment `ember-concurrency`'s `AbstractTaskProperty` interface such that
```ts
import { task } from 'ember-concurrency-decorators';

@task({ withTestWaiter: true })
```
will type-check.

It bumps the `ember-concurrency` dev dependency to `1.3.0` for the `ember-concurrency` types (added in `1.2.0`).

It also adds a section to the readme about usage with TypeScript. It's necessary to manually import the types because users don't import from `ember-concurrency-test-waiter` in their apps.

CC: @chriskrycho @dfreeman @chancancode

### CODE REVIEW

**Comment by bendemboski** [comment]
@jamescdavis thanks for the PR! I just merged a couple of changes that update the dev-deps `ember-concurrency` to the 2.0 beta so we can test against both v1 and v2. Would you mind rebasing your PR branch onto the latest master? Then I'd be happy to merge and cut a release!

**Comment by jamescdavis** [comment]
Thanks for updating this! It had fallen off my radar!

**Comment by jamescdavis** [comment]
@bendemboski I saw you bumped the version to 0.4.0, but I don't see it in https://www.npmjs.com/package/ember-concurrency-test-waiter. Planning to publish soon? 😃

**Comment by bendemboski** [comment]
@jamescdavis haha, whoops, got distracted by something in the middle of things and didn't actually get to the `npm publish` step! Anyway, v0.4.0 is published now.

**Comment by jamescdavis** [comment]
No worries! I totally get that!

**Pull request merged**
